Fix file name and make parameters more understandable
PelionIoT/scripts-pelion-edge pull request #17
Opened 2021-01-29 08:33 UTC by OPpuolitaival

2021-01-29 08:45 UTC, petedyerarm requested changes

2021-01-29 08:45 UTC, petedyerarm commented on ostree/README.md
> +> ./ostree-delta-docker.sh --repo=repo --output=output-dir [--update_repo repo] -- [--to_sha sha] [--from_sha sha]  [--commit message] [--generate_bin]
```suggestion
> ./ostree-delta-docker.sh --repo repo --output output-dir [--update_repo repo] -- [--to_sha sha] [--from_sha sha]  [--commit message] [--generate_bin]
```

2021-02-02 05:57 UTC, cmonr approved these changes

2021-02-02 05:57 UTC, cmonr commented on ostree/README.md
> +> ./ostree-delta-docker.sh --repo=repo --output=output-dir [--update_repo repo] -- [--to_sha sha] [--from_sha sha]  [--commit message] [--generate_bin]
:+1:

2021-02-02 05:58 UTC, cmonr commented
Bringing in. Tweaks look good.

2021-02-02 05:58 UTC, cmonr approved these changes

2021-02-02 06:00 UTC, cmonr commented
Huh. Actually, something looks weird with the view. @petedyerarm, are you able to do anything on your end?

PR says it's waiting on your change request, but imo it was taken in with the new commit.

2021-02-02 09:49 UTC, petedyerarm approved these changes

2021-02-02 09:49 UTC, merged