Add the prepare_combined_update script
PelionIoT/scripts-pelion-edge pull request #41
Opened 2021-12-07 10:04 UTC by davidsaada

This PR adds the `prepare_combined_update.sh` script.

2021-12-07 10:57 UTC, petedyerarm requested changes
The script LGTM.

The top level README.md needs a section describing this new folder.

I assume that the other files (u-boot-caps.its and  16:28 package_conf) are project specific and will be found elsewhere.

2021-12-07 17:22 UTC, davidsaada commented
> The script LGTM.
> 
> The top level README.md needs a section describing this new folder.
> 
> I assume that the other files (u-boot-caps.its and 16:28 package_conf) are project specific and will be found elsewhere.

Thanks @petedyerarm. I'll add the description in the README. As for the accompanied files, they are indeed project specific, but one can argue that this whole script is project specific as well - it assumes 2 images, roots and u-boot, building the capsule for the bootloader, which should be removed once our friends in Foundries add this in the build (which will require us to remove the functionality from this script).

2021-12-08 08:49 UTC, davidsaada commented
@petedyerarm Added README and sample files. @GuyWi Please have a look at the added READMEs.

2021-12-08 09:02 UTC, petedyerarm requested changes

2021-12-08 09:18 UTC, davidsaada commented on combined-update/samples/package_config.yaml
> +  vendor_data: f685ea0469fd37321592246a461a3f0cbfeae48245fc1ad1607bf5d9c28e5699
Done.

2021-12-08 10:27 UTC, petedyerarm approved these changes

2021-12-08 14:39 UTC, JanneKiiskila commented on combined-update/README.md
> +This repository contains helper scripts for combined update.
We should add definition on what we mean with combined update.

2021-12-08 14:55 UTC, JanneKiiskila commented on combined-update/README.md
> +- manifest-package-tool/manifest-dev-tool installation 2.4.0 and higher, initialized to work in the current directory
```suggestion
- manifest-package-tool/manifest-dev-tool installation 2.4.0 or higher, initialized to work in the current directory
```

2021-12-08 14:56 UTC, JanneKiiskila commented on combined-update/README.md
> +
Generic note here, I prefer that filenames are given in the `filename` -syntax. Easier to spot that way.

2021-12-08 14:59 UTC, JanneKiiskila requested changes
Need to explain what a combined update means in the introduction part.

2021-12-09 11:50 UTC, AriParkkila approved these changes

2021-12-10 07:55 UTC, davidsaada commented
@JanneKiiskila addressed all your README comments.

2021-12-10 08:27 UTC, JanneKiiskila approved these changes

2021-12-10 08:32 UTC, merged